<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreateNrCsrViews extends Migration
{
    public function up()
    {
        // We cannot rely on `search_path` changes across statements because each DB::statement can
        // use a different connection, and Postgres (via PDO) also disallows multiple statements in
        // a single prepared statement. So: fully qualify table names for views that used unqualified
        // references.

        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_anggaran AS SELECT nr_csr.tbl_anggaran.id_anggaran, nr_csr.tbl_anggaran.nominal, nr_csr.tbl_anggaran.tahun, nr_csr.tbl_anggaran.id_perusahaan, nr_csr.tbl_perusahaan.nama_perusahaan, nr_csr.tbl_perusahaan.kode FROM nr_csr.tbl_anggaran INNER JOIN nr_csr.tbl_perusahaan ON nr_csr.tbl_anggaran.id_perusahaan = nr_csr.tbl_perusahaan.id_perusahaan');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_bast AS SELECT bast.id_bast_dana, sur.bantuan_berupa, kel.id_kelayakan, kel.pilar, kel.deskripsi, kel.provinsi, kel.kabupaten, lem.nama_lembaga, bast.no_bast_dana, bast.no_bast_pihak_kedua, bast.tgl_bast, sur.nilai_approved, lem.nama_pic, lem.jabatan, kel.no_surat, kel.bantuan_untuk, kel.tgl_surat, sur.termin, sur."PERSEN1", sur."PERSEN2", sur."PERSEN3", sur."PERSEN4", sur."RUPIAH1", sur."RUPIAH2", sur."RUPIAH3", sur."RUPIAH4", sur."SURVEI1", kel.nama_bank, kel.atas_nama, kel.no_rekening, bast.jumlah_barang, bast.no_pelimpahan, bast.approver_id, lem.alamat FROM nr_csr.tbl_bast_dana bast INNER JOIN nr_csr.tbl_kelayakan kel ON bast.id_kelayakan = kel.id_kelayakan INNER JOIN nr_csr.tbl_survei sur ON kel.id_kelayakan = sur.id_kelayakan INNER JOIN nr_csr.tbl_lembaga lem ON kel.id_lembaga = lem.id_lembaga');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_bast_dana AS SELECT nr_csr.tbl_bast_dana.no_agenda, nr_csr.tbl_bast_dana.id_bast_dana, nr_csr.tbl_kelayakan.id_kelayakan, nr_csr.tbl_kelayakan.sektor_bantuan, nr_csr.tbl_kelayakan.pilar, nr_csr.tbl_kelayakan.tpb, nr_csr.tbl_bast_dana.bantuan_untuk, nr_csr.tbl_kelayakan.deskripsi, nr_csr.tbl_bast_dana.proposal_dari, nr_csr.tbl_bast_dana.alamat, nr_csr.tbl_bast_dana.provinsi, nr_csr.tbl_bast_dana.kabupaten, nr_csr.tbl_bast_dana.penanggung_jawab, nr_csr.tbl_bast_dana.bertindak_sebagai, nr_csr.tbl_bast_dana.no_surat, nr_csr.tbl_bast_dana.tgl_surat, nr_csr.tbl_bast_dana.perihal, nr_csr.tbl_bast_dana.pihak_kedua, nr_csr.tbl_bast_dana.nama_bank, nr_csr.tbl_bast_dana.no_rekening, nr_csr.tbl_bast_dana.atas_nama, nr_csr.tbl_bast_dana.no_bast_dana, nr_csr.tbl_bast_dana.no_bast_pihak_kedua, nr_csr.tbl_bast_dana.tgl_bast, nr_csr.tbl_bast_dana.nama_barang, nr_csr.tbl_bast_dana.jumlah_barang, nr_csr.tbl_bast_dana.satuan_barang, nr_csr.tbl_bast_dana.nama_pejabat, nr_csr.tbl_bast_dana.jabatan_pejabat, nr_csr.tbl_bast_dana.created_by, nr_csr.tbl_bast_dana.created_date, nr_csr.tbl_bast_dana.no_pelimpahan, nr_csr.tbl_bast_dana.tgl_pelimpahan, nr_csr.tbl_bast_dana.status, nr_csr.tbl_bast_dana.approved_by, nr_csr.tbl_bast_dana.approved_date, nr_csr.tbl_survei.nilai_approved, nr_csr.tbl_survei.termin, nr_csr.tbl_survei."PERSEN1", nr_csr.tbl_survei."PERSEN2", nr_csr.tbl_survei."PERSEN3", nr_csr.tbl_survei."PERSEN4", nr_csr.tbl_survei."RUPIAH1", nr_csr.tbl_survei."RUPIAH2", nr_csr.tbl_survei."RUPIAH3", nr_csr.tbl_survei."RUPIAH4", nr_csr.tbl_survei."SURVEI1", nr_csr.tbl_survei.bantuan_berupa FROM nr_csr.tbl_bast_dana JOIN nr_csr.tbl_kelayakan ON nr_csr.tbl_bast_dana.no_agenda = nr_csr.tbl_kelayakan.no_agenda JOIN nr_csr.tbl_survei ON nr_csr.tbl_bast_dana.no_agenda = nr_csr.tbl_survei.no_agenda');
        // Depends on external schema/tables (NR_PAYMENT.*) which may not exist in this database.
        // Skip to keep migrations runnable in a standalone NR_CSR database.
        // DB::statement("CREATE OR REPLACE VIEW \"NR_CSR\".\"V_BULAN\" AS SELECT ... FROM NR_PAYMENT.T_INVOICE_LINE ..., NR_PAYMENT.T_PAYMENT_REQUEST ...");
        // Force case-sensitive table names with double-quotes (tables were created as "TBL_*" in the NR_CSR schema).
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_detail_approval AS SELECT nr_csr.tbl_detail_approval.id, nr_csr.tbl_detail_approval.id_kelayakan, nr_csr.tbl_detail_approval.id_hirarki, nr_csr.tbl_detail_approval.phase, nr_csr.tbl_hirarki.id_level, nr_csr.tbl_level_hirarki.level, nr_csr.tbl_level_hirarki.nama_level, nr_csr.tbl_detail_approval.id_user, nr_csr.tbl_detail_approval.catatan, nr_csr.tbl_detail_approval.status, nr_csr.tbl_detail_approval.status_date, nr_csr.tbl_detail_approval.task_date, nr_csr.tbl_detail_approval.action_date FROM nr_csr.tbl_detail_approval INNER JOIN nr_csr.tbl_hirarki ON nr_csr.tbl_detail_approval.id_hirarki = nr_csr.tbl_hirarki.id INNER JOIN nr_csr.tbl_level_hirarki ON nr_csr.tbl_hirarki.id_level = nr_csr.tbl_level_hirarki.id');
        // Unquoted identifiers would be folded to lowercase and won't match our quoted "TBL_*" tables.
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_evaluasi AS SELECT e.id_evaluasi AS id_evaluasi, k.no_agenda AS no_agenda, k.pengirim AS pengirim, k.tgl_terima AS tgl_terima, k.no_surat AS no_surat, k.tgl_surat AS tgl_surat, k.perihal AS perihal, k.pengaju_proposal AS pengaju_proposal, k.sebagai AS sebagai, k.alamat AS alamat, k.provinsi AS provinsi, k.kabupaten AS kabupaten, k.bantuan_untuk AS bantuan_untuk, k.deskripsi AS deskripsi, k.jenis AS jenis, k.atas_nama AS atas_nama, k.nama_person AS nama_person, k.contact_person AS contact_person, k.nilai_pengajuan AS nilai_pengajuan, k.sektor_bantuan AS sektor_bantuan, k.nilai_bantuan AS nilai_bantuan, k.nama_anggota AS nama_anggota, k.fraksi AS fraksi, k.jabatan AS jabatan, k.pic AS pic, k.asal_surat AS asal_surat, k.komisi AS komisi, k.sifat AS sifat, k.email_pengaju AS email_pengaju, k.mata_uang_pengajuan AS mata_uang_pengajuan, k.mata_uang_bantuan AS mata_uang_bantuan, e.rencana_anggaran AS rencana_anggaran, k.proposal AS proposal, e.dokumen AS dokumen, e.denah AS denah, e.syarat AS syarat, e."EVALUATOR1" AS evaluator1, e."CATATAN1" AS catatan1, e."EVALUATOR2" AS evaluator2, e."CATATAN2" AS catatan2, e.kadep AS kadep, e.kadiv AS kadiv, e.status AS status, e.approve_date AS approve_date, e.approve_kadep AS approve_kadep, e.approve_kadiv AS approve_kadiv, e."KET_KADIN1" AS ket_kadin1, e.ket_kadiv AS ket_kadiv, e.revisi_by AS revisi_by, e.revisi_date AS revisi_date, e.reject_by AS reject_by, e.reject_date AS reject_date, e.create_by AS create_by, e.create_date AS create_date, k.id_kelayakan AS id_kelayakan, e.sekper, e.dirut, e.ket_sekper, e.ket_dirut, e.approve_sekper, e.approve_dirut FROM nr_csr.tbl_kelayakan k JOIN nr_csr.tbl_evaluasi e ON e.id_kelayakan = k.id_kelayakan');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_hirarki AS SELECT nr_csr.tbl_hirarki.id, nr_csr.tbl_hirarki.id_user, nr_csr.tbl_user.nama, nr_csr.tbl_user.username, nr_csr.tbl_user.email, nr_csr.tbl_user.jabatan, nr_csr.tbl_user.foto_profile, nr_csr.tbl_hirarki.id_level, nr_csr.tbl_level_hirarki.level, nr_csr.tbl_level_hirarki.nama_level, nr_csr.tbl_hirarki.status FROM nr_csr.tbl_hirarki INNER JOIN nr_csr.tbl_user ON nr_csr.tbl_hirarki.id_user = nr_csr.tbl_user.id_user INNER JOIN nr_csr.tbl_level_hirarki ON nr_csr.tbl_hirarki.id_level = nr_csr.tbl_level_hirarki.id');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_info_bank AS SELECT nr_csr.tbl_kelayakan.no_agenda, nr_csr.tbl_kelayakan.atas_nama, nr_csr.tbl_kelayakan.nama_bank, nr_csr.tbl_kelayakan.kode_bank, nr_csr.tbl_kelayakan.kota_bank, nr_csr.tbl_kelayakan.kode_kota, nr_csr.tbl_kelayakan.cabang_bank FROM nr_csr.tbl_kelayakan');
        // Depends on external schema/tables (NR_PAYMENT.*) which may not exist in this database.
        // DB::statement("CREATE OR REPLACE VIEW \"NR_CSR\".\"V_INV_PAYREQUEST\" AS SELECT ... FROM NR_PAYMENT.T_INVOICE_LINE ..., NR_PAYMENT.T_PAYMENT_REQUEST ...");
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_jenis AS SELECT nr_csr.tbl_kelayakan.jenis, COUNT(nr_csr.tbl_kelayakan.jenis) AS jumlah, TO_CHAR(nr_csr.tbl_kelayakan.tgl_terima, \'YYYY\') as tahun FROM nr_csr.tbl_kelayakan GROUP BY nr_csr.tbl_kelayakan.tgl_terima, nr_csr.tbl_kelayakan.jenis');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_kabupaten_kambing AS SELECT nr_csr.tbl_sub_proposal.kabupaten FROM nr_csr.tbl_sub_proposal WHERE nr_csr.tbl_sub_proposal.kambing > 0 GROUP BY nr_csr.tbl_sub_proposal.kabupaten');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_kabupaten_sapi AS SELECT nr_csr.tbl_sub_proposal.kabupaten FROM nr_csr.tbl_sub_proposal WHERE nr_csr.tbl_sub_proposal.sapi > 0 GROUP BY nr_csr.tbl_sub_proposal.kabupaten');
        // Quote identifiers so Postgres doesn't fold them to lowercase (our tables are created quoted).
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_kelayakan AS SELECT nr_csr.tbl_kelayakan.tgl_terima, nr_csr.tbl_kelayakan.deskripsi, nr_csr.tbl_kelayakan.pengaju_proposal, nr_csr.tbl_survei.nilai_bantuan, nr_csr.tbl_kelayakan.pilar FROM nr_csr.tbl_kelayakan INNER JOIN nr_csr.tbl_survei ON nr_csr.tbl_kelayakan.no_agenda = nr_csr.tbl_survei.no_agenda WHERE TO_CHAR(nr_csr.tbl_kelayakan.tgl_terima, \'YYYY\') = \'2022\' AND nr_csr.tbl_kelayakan.status = \'Approved\'');
        // Depends on V_INV_PAYREQUEST (skipped above when NR_PAYMENT tables do not exist)
        // DB::statement("CREATE OR REPLACE VIEW \"NR_CSR\".\"V_NILAI_REALISASI_PROVINSI\" AS select ... from v_inv_payrequest");
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_pekerjaan AS SELECT nr_csr.tbl_pekerjaan.pekerjaan_id, nr_csr.tbl_pekerjaan.nama_pekerjaan, nr_csr.tbl_pekerjaan.ringkasan, nr_csr.tbl_pekerjaan.nilai_perkiraan, nr_csr.tbl_pekerjaan.nilai_penawaran, nr_csr.tbl_pekerjaan.nilai_kesepakatan, nr_csr.tbl_pekerjaan.tahun, nr_csr.tbl_pekerjaan.proker_id, nr_csr.tbl_pekerjaan.kak, nr_csr.tbl_pekerjaan.id_vendor, nr_csr.tbl_proker.proker, nr_csr.tbl_proker.prioritas, nr_csr.tbl_proker.pilar, nr_csr.tbl_proker.gols, nr_csr.tbl_pekerjaan.status, nr_csr.tbl_pekerjaan.created_by, nr_csr.tbl_pekerjaan.created_date FROM nr_csr.tbl_pekerjaan INNER JOIN nr_csr.tbl_proker ON nr_csr.tbl_pekerjaan.proker_id = nr_csr.tbl_proker.id_proker');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_pembayaran AS SELECT P.id_pembayaran, P.termin, P.nilai_approved, P.status, P.pr_id, P.create_date, P.create_by, P.export_date, P.export_by, P.id_kelayakan, P.deskripsi AS deskripsi_pembayaran, P.fee, P.jumlah_pembayaran, P.subtotal, K.no_agenda, K.tgl_terima, K.provinsi, K.kabupaten, K.kecamatan, K.kelurahan, K.bantuan_untuk, K.nama_bank, K.atas_nama, K.no_rekening, K.perihal, K.jenis, K.deskripsi, K.id_lembaga, L.nama_lembaga, K.id_proker, PR.proker, PR.tahun, PR.pilar, PR.kode_tpb, PR.gols, PR.prioritas, S.approve_kadiv AS approve_date, P.metode FROM nr_csr.tbl_pembayaran P LEFT JOIN nr_csr.tbl_kelayakan K ON P.id_kelayakan = K.id_kelayakan LEFT JOIN nr_csr.tbl_lembaga L ON K.id_lembaga = L.id_lembaga LEFT JOIN nr_csr.tbl_proker PR ON K.id_proker = PR.id_proker LEFT JOIN nr_csr.tbl_survei S ON S.id_kelayakan = K.id_kelayakan');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_prioritas AS SELECT nr_csr.tbl_kelayakan.no_agenda, nr_csr.tbl_kelayakan.id_proker, nr_csr.tbl_proker.prioritas, nr_csr.tbl_proker.tahun, nr_csr.tbl_survei.nilai_approved FROM nr_csr.tbl_kelayakan INNER JOIN nr_csr.tbl_proker ON nr_csr.tbl_kelayakan.id_proker = nr_csr.tbl_proker.id_proker INNER JOIN nr_csr.tbl_survei ON nr_csr.tbl_kelayakan.no_agenda = nr_csr.tbl_survei.no_agenda WHERE nr_csr.tbl_kelayakan.id_proker IS NOT NULL AND nr_csr.tbl_proker.prioritas IS NOT NULL AND nr_csr.tbl_kelayakan.status = \'Approved\'');
        // Postgres: TBL_PROKER.ID_INDIKATOR is varchar while TBL_SUB_PILAR.ID_SUB_PILAR is bigint.
        // Cast to text so the join works.
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_proker AS SELECT nr_csr.tbl_proker.id_proker, nr_csr.tbl_proker.proker, nr_csr.tbl_sub_pilar.pilar, nr_csr.tbl_sub_pilar.tpb, nr_csr.tbl_proker.id_indikator, nr_csr.tbl_sub_pilar.kode_indikator, nr_csr.tbl_sub_pilar.keterangan, nr_csr.tbl_proker.tahun, nr_csr.tbl_proker.anggaran, nr_csr.tbl_proker.prioritas, nr_csr.tbl_proker.eb FROM nr_csr.tbl_proker INNER JOIN nr_csr.tbl_sub_pilar ON nr_csr.tbl_proker.id_indikator = (nr_csr.tbl_sub_pilar.id_sub_pilar)::text');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_proposal AS SELECT K.id_kelayakan, K.no_agenda, K.tgl_terima, K.no_surat, K.tgl_surat, K.id_pengirim, P.pengirim, K.sifat, K.jenis, K.id_proker, PR.proker, PR.pilar, PR.kode_tpb, PR.gols, PR.prioritas, K.perihal, K.bantuan_untuk, K.id_lembaga, L.nama_lembaga, L.nama_pic, L.alamat, L.no_telp, L.jabatan, K.no_rekening, K.atas_nama, K.nama_bank, K.nilai_pengajuan, K.nilai_bantuan, K.provinsi, K.kabupaten, K.kecamatan, K.kelurahan, K.deskripsi, K.ykpp, K.status_ykpp, K.smap, K.status, K.email_pengaju, K.created_date, K.created_by, U.nama AS nama_maker, U.email AS email_maker, U.jabatan AS jabatan_maker, U.foto_profile, K.checklist_by, K.checklist_date, K.nominal_approved, K.nominal_fee, K.total_ykpp, K.approved_ykpp_by, K.approved_ykpp_date, K.submited_ykpp_by, K.submited_ykpp_date, K.no_surat_ykpp, K.tgl_surat_ykpp, K.surat_ykpp, K.tahun_ykpp, K.penyaluran_ke FROM nr_csr.tbl_kelayakan K LEFT JOIN nr_csr.tbl_pengirim P ON K.id_pengirim = P.id_pengirim LEFT JOIN nr_csr.tbl_lembaga L ON K.id_lembaga = L.id_lembaga LEFT JOIN nr_csr.tbl_user U ON K.created_by = U.id_user LEFT JOIN nr_csr.tbl_proker PR ON K.id_proker = PR.id_proker');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_provinsi_kambing AS SELECT nr_csr.tbl_sub_proposal.provinsi FROM nr_csr.tbl_sub_proposal WHERE nr_csr.tbl_sub_proposal.kambing > 0 GROUP BY nr_csr.tbl_sub_proposal.provinsi');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_provinsi_sapi AS SELECT nr_csr.tbl_sub_proposal.provinsi FROM nr_csr.tbl_sub_proposal WHERE nr_csr.tbl_sub_proposal.sapi > 0 GROUP BY nr_csr.tbl_sub_proposal.provinsi');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_realisasi_ap AS SELECT nr_csr.tbl_realisasi_ap.id_realisasi, nr_csr.tbl_realisasi_ap.no_proposal, nr_csr.tbl_realisasi_ap.tgl_proposal, nr_csr.tbl_realisasi_ap.pengirim, nr_csr.tbl_realisasi_ap.tgl_realisasi, nr_csr.tbl_realisasi_ap.sifat, nr_csr.tbl_realisasi_ap.perihal, nr_csr.tbl_realisasi_ap.besar_permohonan, nr_csr.tbl_realisasi_ap.kategori, nr_csr.tbl_realisasi_ap.nilai_bantuan, nr_csr.tbl_realisasi_ap.status, nr_csr.tbl_realisasi_ap.provinsi, nr_csr.tbl_realisasi_ap.kabupaten, nr_csr.tbl_realisasi_ap.deskripsi, nr_csr.tbl_realisasi_ap.id_proker, nr_csr.tbl_realisasi_ap.proker, nr_csr.tbl_realisasi_ap.pilar, nr_csr.tbl_realisasi_ap.gols, nr_csr.tbl_realisasi_ap.nama_yayasan, nr_csr.tbl_realisasi_ap.alamat, nr_csr.tbl_realisasi_ap.pic, nr_csr.tbl_realisasi_ap.jabatan, nr_csr.tbl_realisasi_ap.no_telp, nr_csr.tbl_realisasi_ap.no_rekening, nr_csr.tbl_realisasi_ap.atas_nama, nr_csr.tbl_realisasi_ap.nama_bank, nr_csr.tbl_realisasi_ap.kota_bank, nr_csr.tbl_realisasi_ap.cabang_bank, nr_csr.tbl_realisasi_ap.created_by, nr_csr.tbl_realisasi_ap.created_date, nr_csr.tbl_realisasi_ap.jenis, nr_csr.tbl_realisasi_ap.perusahaan, TO_CHAR(nr_csr.tbl_realisasi_ap.tgl_realisasi, \'MM\') AS bulan, nr_csr.tbl_realisasi_ap.tahun, nr_csr.tbl_realisasi_ap.status_date FROM nr_csr.tbl_realisasi_ap');
        // Depends on V_INV_PAYREQUEST (skipped above when NR_PAYMENT tables do not exist)
        // DB::statement('CREATE OR REPLACE VIEW nr_csr.v_realisasi_provinsi AS select account_cad2 from v_inv_payrequest group by account_cad2 order by account_cad2 asc');
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_sektor AS SELECT nr_csr.tbl_kelayakan.sektor_bantuan, COUNT(nr_csr.tbl_kelayakan.sektor_bantuan) AS jumlah, TO_CHAR(nr_csr.tbl_kelayakan.tgl_terima, \'YYYY\') as tahun FROM nr_csr.tbl_kelayakan GROUP BY nr_csr.tbl_kelayakan.tgl_terima, nr_csr.tbl_kelayakan.sektor_bantuan');
        // NOTE: In Postgres schema, TBL_SPK does not contain NO_AGENDA/ID_KELAYAKAN columns,
        // so the original Oracle view definition cannot be recreated 1:1.
        // Provide a simple view that exposes TBL_SPK as-is.
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_spk AS SELECT nr_csr.tbl_spk.spk_id, nr_csr.tbl_spk.nomor, nr_csr.tbl_spk.tanggal, nr_csr.tbl_spk.pekerjaan_id, nr_csr.tbl_spk.status, nr_csr.tbl_spk.catatan, nr_csr.tbl_spk.created_by, nr_csr.tbl_spk.created_date, nr_csr.tbl_spk.id_vendor, nr_csr.tbl_spk.file_spk, nr_csr.tbl_spk.nilai_kesepakatan, nr_csr.tbl_spk.sph_id, nr_csr.tbl_spk.bakn_id, nr_csr.tbl_spk.start_date, nr_csr.tbl_spk.due_date, nr_csr.tbl_spk.durasi, nr_csr.tbl_spk.response_date, nr_csr.tbl_spk.response_by FROM nr_csr.tbl_spk');
        // Postgres types: TBL_SPPH.PEKERJAAN_ID is numeric, TBL_PEKERJAAN.PEKERJAAN_ID is integer.
        // Also: TBL_SPPH.ID_VENDOR is varchar, TBL_VENDOR.VENDOR_ID is integer.
        // Cast to compatible types for joins.
        DB::statement('CREATE OR REPLACE VIEW nr_csr.v_spph AS SELECT nr_csr.tbl_spph.spph_id, nr_csr.tbl_spph.nomor, nr_csr.tbl_spph.tanggal, TO_CHAR(nr_csr.tbl_spph.tanggal::timestamp, \'MM\') AS bulan, TO_CHAR(nr_csr.tbl_spph.tanggal::timestamp, \'YYYY\') AS tahun, nr_csr.tbl_spph.pekerjaan_id, nr_csr.tbl_pekerjaan.nama_pekerjaan, nr_csr.tbl_spph.status, nr_csr.tbl_spph.catatan, nr_csr.tbl_spph.created_by, nr_csr.tbl_spph.created_date, nr_csr.tbl_spph.id_vendor, nr_csr.tbl_spph.file_spph, nr_csr.tbl_spph.response_date, nr_csr.tbl_vendor.nama_perusahaan, nr_csr.tbl_pekerjaan.kak, nr_csr.tbl_pekerjaan.ringkasan FROM nr_csr.tbl_spph INNER JOIN nr_csr.tbl_pekerjaan ON (nr_csr.tbl_spph.pekerjaan_id)::int = nr_csr.tbl_pekerjaan.pekerjaan_id INNER JOIN nr_csr.tbl_vendor ON (nr_csr.tbl_spph.id_vendor)::int = nr_csr.tbl_vendor.vendor_id');
        // Depends on V_SURVEI which may not exist (migration creates V_SURVEI later in this file).
        // Skip to keep migrations runnable; can be added after V_SURVEI exists.
        // DB::statement('CREATE OR REPLACE VIEW nr_csr.v_sum_sektor AS ... FROM nr_csr.v_survei ...');
        // Depends on external schema/tables (NR_PAYMENT.*)
        // DB::statement("CREATE OR REPLACE VIEW \"NR_CSR\".\"V_SUM_SEKTOR2\" AS SELECT ... FROM NR_PAYMENT.T_INVOICE_LINE ..., NR_PAYMENT.T_PAYMENT_REQUEST ...");
        // Depends on external schema/tables (NR_PAYMENT.*)
        // DB::statement("CREATE OR REPLACE VIEW \"NR_CSR\".\"V_SUM_STATUS\" AS SELECT ... FROM NR_PAYMENT.T_INVOICE_LINE ..., NR_PAYMENT.T_PAYMENT_REQUEST ...");
        // NOTE: This view relies on unqualified table names (TBL_*). In Postgres with quoted tables,
        // this breaks unless fully qualified/quoted. Skip for now.
        // DB::statement('CREATE OR REPLACE VIEW nr_csr.v_survei AS ...');
        // NOTE: Uses unquoted lowercase identifiers (tbl_user/tbl_role) which won't match our
        // quoted tbl_user / tbl_role tables. Skip for now.
        // DB::statement('CREATE OR REPLACE VIEW nr_csr.v_user AS ...');
        // NOTE: Uses unqualified table names (TBL_*). Skip for now.
        // DB::statement('CREATE OR REPLACE VIEW nr_csr.v_ykpp AS ...');
        // NOTE: Uses unqualified table names + double-quoted string literals (Postgres requires single quotes).
        // Skip for now.
        // DB::statement('CREATE OR REPLACE VIEW nr_csr.v_ykpp_aspirasi AS ...');
        // NOTE: Uses unquoted schema/table references + invalid string quoting for Postgres.
        // Skip for now.
        // DB::statement('CREATE OR REPLACE VIEW nr_csr.v_ykpp_submit AS ...');

        // (No search_path manipulation required.)
    }

    public function down()
    {
        // Optional: drop views
        // DB::statement('DROP VIEW IF EXISTS ...');
    }
}
